hub:
  image: selenium/hub:3.4.0
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox-debug:3.4.0
  links:
    - hub
  ports:
    - "5900"
  volumes:
    - ./assets:/User/assets
chrome:
  image: selenium/node-chrome-debug:3.4.0
  ports:
    - "5900"
  links:
    - hub
  volumes:
    - ./assets:/User/assets